-- MySQL Script generated by MySQL Workbench
-- Tue May 19 13:22:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aquapark_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aquapark_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aquapark_db` DEFAULT CHARACTER SET utf8 ;
USE `aquapark_db` ;

-- -----------------------------------------------------
-- Table `aquapark_db`.`Gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`Gender` (
  `genderId` INT NOT NULL,
  `genderName` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`genderId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`User` (
  `userId` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `contactNumber` VARCHAR(45) NULL,
  `otherInformation` VARCHAR(45) NULL,
  `userName` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `pesel` VARCHAR(45) NULL,
  `birthDate` DATE NULL,
  `genderId` INT NOT NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_user_gender_idx` (`genderId` ASC) INVISIBLE,
  CONSTRAINT `fk_user_gender`
    FOREIGN KEY (`genderId`)
    REFERENCES `aquapark_db`.`Gender` (`genderId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`Client` (
  `clientId` INT NOT NULL,
  `ownsAccount` TINYINT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`clientId`),
  INDEX `fk_client_user_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_client_user`
    FOREIGN KEY (`userId`)
    REFERENCES `aquapark_db`.`User` (`userId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`ClientIdentificator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`ClientIdentificator` (
  `identificatorId` INT NOT NULL,
  `isInUse` TINYINT NOT NULL,
  PRIMARY KEY (`identificatorId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`Visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`Visit` (
  `visitId` INT NOT NULL,
  `date` DATE NOT NULL,
  `startTime` TIME NOT NULL,
  `endTime` TIME NULL,
  `value` DECIMAL(15,5) NOT NULL,
  `identificatorId` INT NOT NULL,
  `clientId` INT NOT NULL,
  PRIMARY KEY (`visitId`),
  INDEX `fk_visit_clientidentificator_idx` (`identificatorId` ASC) VISIBLE,
  INDEX `fk_visit_user_idx` (`clientId` ASC) INVISIBLE,
  CONSTRAINT `fk_visit_user`
    FOREIGN KEY (`clientId`)
    REFERENCES `aquapark_db`.`Client` (`clientId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_visit_clientidentificator`
    FOREIGN KEY (`identificatorId`)
    REFERENCES `aquapark_db`.`ClientIdentificator` (`identificatorId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`Employee` (
  `employeeId` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`employeeId`),
  INDEX `fk_employee_user_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_employee_user`
    FOREIGN KEY (`userId`)
    REFERENCES `aquapark_db`.`User` (`userId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`Role` (
  `roleId` INT NOT NULL,
  `roleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`PriceList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`PriceList` (
  `priceListId` INT NOT NULL,
  `validityStartDate` DATE NOT NULL,
  `employeeId` INT NOT NULL,
  PRIMARY KEY (`priceListId`),
  INDEX `fk_pricelist_employee_idx` (`employeeId` ASC) VISIBLE,
  CONSTRAINT `fk_pricelist_employee`
    FOREIGN KEY (`employeeId`)
    REFERENCES `aquapark_db`.`Employee` (`employeeId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`AquaparkAttraction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`AquaparkAttraction` (
  `attractionId` INT NOT NULL,
  `maxUsers` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`attractionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`AquaparkAttractionMaintenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`AquaparkAttractionMaintenance` (
  `attractionMaintenanceId` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `date` DATE NOT NULL,
  `employeeId` INT NOT NULL,
  `attractionId` INT NOT NULL,
  PRIMARY KEY (`attractionMaintenanceId`),
  INDEX `fk_aquaparkattractionmaintenance_employee_idx` (`employeeId` ASC) INVISIBLE,
  INDEX `fk_aquaparkattractionmaintenance_aquaparkattraction_idx` (`attractionId` ASC) VISIBLE,
  CONSTRAINT `fk_aquaparkattractionmaintenance_employee`
    FOREIGN KEY (`employeeId`)
    REFERENCES `aquapark_db`.`Employee` (`employeeId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_aquaparkattractionmaintenance_aquaparkattraction`
    FOREIGN KEY (`attractionId`)
    REFERENCES `aquapark_db`.`AquaparkAttraction` (`attractionId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`Conditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`Conditions` (
  `conditionId` INT NOT NULL,
  `weekendOnly` TINYINT NOT NULL,
  `childOnly` TINYINT NOT NULL,
  `seniorOnly` TINYINT NOT NULL,
  PRIMARY KEY (`conditionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`PriceListItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`PriceListItem` (
  `priceListItemId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `value` DECIMAL(15,5) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `priceListId` INT NOT NULL,
  `conditionalId` INT NOT NULL,
  `attractionId` INT NOT NULL,
  PRIMARY KEY (`priceListItemId`),
  INDEX `fk_pricelistitem_conditions_idx` (`conditionalId` ASC) INVISIBLE,
  INDEX `fk_pricelistitem_pricelist_idx` (`priceListId` ASC) INVISIBLE,
  INDEX `fk_priceListItem_aquaparkattraction_idx` (`attractionId` ASC) INVISIBLE,
  CONSTRAINT `fk_pricelistitem_pricelist`
    FOREIGN KEY (`priceListId`)
    REFERENCES `aquapark_db`.`PriceList` (`priceListId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_pricelistitem_conditions`
    FOREIGN KEY (`conditionalId`)
    REFERENCES `aquapark_db`.`Conditions` (`conditionId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_priceListItem_aquaparkattraction_idx`
    FOREIGN KEY (`attractionId`)
    REFERENCES `aquapark_db`.`AquaparkAttraction` (`attractionId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`AquaparkAttractionGate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`AquaparkAttractionGate` (
  `gateId` INT NOT NULL,
  `attractionId` INT NOT NULL,
  PRIMARY KEY (`gateId`),
  INDEX `fk_aquaparkattractiongate_aquaparkattraction_idx` (`attractionId` ASC) VISIBLE,
  CONSTRAINT `fk_aquaparkattractiongate_aquaparkattraction`
    FOREIGN KEY (`attractionId`)
    REFERENCES `aquapark_db`.`AquaparkAttraction` (`attractionId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`AquaparkAttractionGateEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`AquaparkAttractionGateEvent` (
  `eventId` INT NOT NULL,
  `isEntering` TINYINT NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `gateId` INT NOT NULL,
  `identificatorId` INT NOT NULL,
  PRIMARY KEY (`eventId`),
  INDEX `fk_aquaparkattractiongateevent_aquaparkattractiongate_idx` (`gateId` ASC) INVISIBLE,
  INDEX `fk_aquaparkattractiongateevent_clientidentificator_idx` (`identificatorId` ASC) VISIBLE,
  CONSTRAINT `fk_aquaparkattractiongateevent_aquaparkattractiongate`
    FOREIGN KEY (`gateId`)
    REFERENCES `aquapark_db`.`AquaparkAttractionGate` (`gateId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_aquaparkattractiongateevent_clientidentificator`
    FOREIGN KEY (`identificatorId`)
    REFERENCES `aquapark_db`.`ClientIdentificator` (`identificatorId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`AquaparkAttractionUsage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`AquaparkAttractionUsage` (
  `usageId` INT NOT NULL,
  `attractionId` INT NOT NULL,
  `priceListItemId` INT NOT NULL,
  `visitId` INT NOT NULL,
  `enteringEventId` INT NOT NULL,
  `leavingEventId` INT NULL,
  PRIMARY KEY (`usageId`),
  INDEX `fk_aquaparkattracionusage_aquaparkattraction_idx` (`attractionId` ASC) INVISIBLE,
  INDEX `fk_aquaparkattracionusage_pricelistitem_idx` (`priceListItemId` ASC) VISIBLE,
  INDEX `fk_aquaparkattracionusage_visit_idx` (`visitId` ASC) VISIBLE,
  INDEX `fk_aquaparkattracionusage_aquaparkattractiongateevent_enter_idx` (`enteringEventId` ASC) INVISIBLE,
  INDEX `fk_aquaparkattracionusage_aquaparkattractiongateevent_leave_idx` (`leavingEventId` ASC) INVISIBLE,
  CONSTRAINT `fk_aquaparkattracionusage_aquaparkattraction`
    FOREIGN KEY (`attractionId`)
    REFERENCES `aquapark_db`.`AquaparkAttraction` (`attractionId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_aquaparkattracionusage_pricelistitem`
    FOREIGN KEY (`priceListItemId`)
    REFERENCES `aquapark_db`.`PriceListItem` (`priceListItemId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_aquaparkattracionusage_visit`
    FOREIGN KEY (`visitId`)
    REFERENCES `aquapark_db`.`Visit` (`visitId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_aquaparkattracionusage_aquaparkattractiongateevent_enter`
    FOREIGN KEY (`enteringEventId`)
    REFERENCES `aquapark_db`.`AquaparkAttractionGateEvent` (`eventId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_aquaparkattracionusage_aquaparkattractiongateevent_leave`
    FOREIGN KEY (`leavingEventId`)
    REFERENCES `aquapark_db`.`AquaparkAttractionGateEvent` (`eventId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aquapark_db`.`Role_has_Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aquapark_db`.`Role_has_Employee` (
  `roleId` INT NOT NULL,
  `employeeId` INT NOT NULL,
  PRIMARY KEY (`roleId`, `employeeId`),
  INDEX `fk_Role_has_Employee_Employee1_idx` (`employeeId` ASC) VISIBLE,
  INDEX `fk_Role_has_Employee_Role1_idx` (`roleId` ASC) VISIBLE,
  CONSTRAINT `roleId`
    FOREIGN KEY (`roleId`)
    REFERENCES `aquapark_db`.`Role` (`roleId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `employeeId`
    FOREIGN KEY (`employeeId`)
    REFERENCES `aquapark_db`.`Employee` (`employeeId`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
