SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE aquapark_db.aquaparkattraction;
TRUNCATE TABLE aquapark_db.aquaparkattractiongate;
TRUNCATE TABLE aquapark_db.aquaparkattractiongateevent;
TRUNCATE TABLE aquapark_db.aquaparkattractionmaintenance;
TRUNCATE TABLE aquapark_db.aquaparkattractionusage;
TRUNCATE TABLE aquapark_db.client;
TRUNCATE TABLE aquapark_db.clientidentificator;
TRUNCATE TABLE aquapark_db.conditions;
TRUNCATE TABLE aquapark_db.employee;
TRUNCATE TABLE aquapark_db.gender;
TRUNCATE TABLE aquapark_db.pricelist;
TRUNCATE TABLE aquapark_db.pricelistitem;
TRUNCATE TABLE aquapark_db.role;
TRUNCATE TABLE aquapark_db.role_has_employee;
TRUNCATE TABLE aquapark_db.spring_session;
TRUNCATE TABLE aquapark_db.spring_session_attributes;
TRUNCATE TABLE aquapark_db.user;
TRUNCATE TABLE aquapark_db.visit;
SET FOREIGN_KEY_CHECKS=1;